// Web/src/app/footer/footer.component.ts
import { Component } from '@angular/core';

import { NzFlexModule } from 'ng-zorro-antd/flex';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzLayoutModule } from 'ng-zorro-antd/layout';
import { NzTypographyModule } from 'ng-zorro-antd/typography';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [NzLayoutModule, NzIconModule, NzFlexModule, NzTypographyModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  email = 'oleksandr.zwick@gmail.com';
}

<nz-footer>
  <div nz-flex nzAlign="center" nzJustify="space-between" nzGap="middle" nzWrap="wrap">
    <div nz-flex nzGap="large" nzWrap="wrap">
      <span>Terview</span>
      <span>Dashboard</span>
    </div>
    <span class="copyright">
      © 2024. Copyright:
      <span nz-typography>
        <a href="mailto:{{ email }}">{{ email }}</a>
      </span>
    </span>
    <nav nz-flex class="social-links" nzGap="large" nzWrap="wrap">
      <a href="https://linkedin.com/in/oleksandr-tsvik" target="_blank">
        <span nz-icon nzType="linkedin" nzTheme="outline"></span>
      </a>
      <a href="https://github.com/OleksandrTsvik" target="_blank">
        <span nz-icon nzType="github" nzTheme="outline"></span>
      </a>
      <a href="mailto:{{ email }}">
        <span nz-icon nzType="mail" nzTheme="outline"></span>
      </a>
    </nav>
  </div>
</nz-footer>

// Web/src/features/layout/footer/index.tsx
import { GithubOutlined, LinkedinOutlined, MailOutlined } from '@ant-design/icons';
import { Flex, Layout } from 'antd';
import { Link } from 'react-router';

import styles from './footer.module.scss';

export default function Footer() {
  const email = 'oleksandr.zwick@gmail.com';

  return (
    <Layout.Footer className={styles.footer}>
      <Flex gap="large" wrap="wrap">
        <Link to="/">Home</Link>
        <Link to="/dashboard">Dashboard</Link>
      </Flex>
      <span className={styles.copyright}>
        © 2024. Copyright: <Link to={`mailto:${email}`}>{email}</Link>
      </span>
      <Flex className={styles.socialLinks} component="nav" gap="large" wrap="wrap">
        <Link to="https://linkedin.com/in/oleksandr-tsvik" target="_blank">
          <LinkedinOutlined />
        </Link>
        <Link to="https://github.com/OleksandrTsvik" target="_blank">
          <GithubOutlined />
        </Link>
        <Link to={`mailto:${email}`}>
          <MailOutlined />
        </Link>
      </Flex>
    </Layout.Footer>
  );
}
